In [5]:
import numpy as np
import torch

创建tensor

In [3]:
# 创建tensor
# 1.import from numpy
a = np.array([2, 3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [7]:
a = np.ones([2, 3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
# 2.import from list
torch.tensor([2., 3.2])

tensor([2.0000, 3.2000])

In [9]:
torch.FloatTensor([2., 3.2])

tensor([2.0000, 3.2000])

In [6]:
torch.tensor([[2., 3.2],
              [1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

uninitialized

In [12]:
# uninitialized
torch.empty(1)

tensor([2.3694e-38])

In [15]:
torch.Tensor(2, 3)

tensor([[-1.4975e+12,  4.5912e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [3]:
torch.IntTensor(2, 3)

tensor([[ 538976266, 1044266528,  537555744],
        [1948262432, 1869835877,  542845042]], dtype=torch.int32)

In [4]:
torch.FloatTensor(2, 3)

tensor([[1.0901e+27, 1.1022e+24, 7.2734e+22],
        [4.7429e+30, 2.8231e+23, 6.8608e+22]])

set default type

In [8]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [11]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

rand/rand_like, randint

In [12]:
torch.rand(3, 3)

tensor([[0.3856, 0.5983, 0.1606],
        [0.8733, 0.0217, 0.7903],
        [0.0814, 0.1587, 0.4059]])

In [13]:
a = torch.rand(3, 3)
torch.rand_like(a)

tensor([[0.8151, 0.1595, 0.2944],
        [0.9719, 0.3844, 0.3346],
        [0.7221, 0.2095, 0.0546]])

In [17]:
torch.randint(1, 10,(3, 3))
torch.randint(1, 10,(3, 3)).type()

'torch.LongTensor'

randn

In [18]:
torch.randn(3, 3)

tensor([[-0.7167, -2.0408,  1.3695],
        [ 0.2150,  1.2503, -0.1751],
        [-0.0160,  0.2701,  2.3544]])

In [27]:
torch.full([10], 0)
torch.arange(1, 0, -0.1)
torch.normal(mean=torch.full([10], 0), std=torch.arange(1, 0, -0.1))

tensor([-0.1021,  0.8877,  0.1535, -0.0929, -0.5594, -0.2850,  0.4596, -0.5110,
         0.0291,  0.1723])

full

In [23]:
torch.full([2, 3], 7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

In [24]:
torch.full([], 7)

tensor(7.)

In [28]:
torch.full([1], 7)

tensor([7.])

arange/range

In [29]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [32]:
torch.range(0, 10)

D:\Anaconda\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

linspace/logspace

In [36]:
torch.linspace(0, 10, steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [34]:
torch.linspace(0, 10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [37]:
torch.linspace(0, 10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
torch.logspace(0, -1, steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [39]:
torch.logspace(0, 1, steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

ones/zeros/eye

In [40]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [41]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [42]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [43]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [44]:
a = torch.zeros(3, 3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

randperm

In [46]:
torch.randperm(10)

tensor([3, 1, 9, 7, 8, 4, 6, 5, 2, 0])

In [51]:
a = torch.rand(2, 3)
b = torch.rand(2, 2)
idx = torch.randperm(2)
idx

tensor([0, 1])

In [52]:
a[idx]

tensor([[0.8520, 0.7300, 0.4481],
        [0.2664, 0.3506, 0.2617]])

In [53]:
b[idx]

tensor([[0.1182, 0.0766],
        [0.1253, 0.1186]])

In [54]:
a,b

(tensor([[0.8520, 0.7300, 0.4481],
         [0.2664, 0.3506, 0.2617]]), tensor([[0.1182, 0.0766],
         [0.1253, 0.1186]]))