In [6]:
import torch

# view reshape

In [4]:
a = torch.rand(4, 1, 28,28)
a.shape

torch.Size([4, 1, 28, 28])

In [5]:
a.view(4, 28*28)

tensor([[0.2212, 0.8980, 0.9834,  ..., 0.3075, 0.6593, 0.2300],
        [0.5197, 0.0888, 0.5943,  ..., 0.3329, 0.2384, 0.4015],
        [0.3936, 0.1611, 0.0521,  ..., 0.0299, 0.2759, 0.5953],
        [0.5999, 0.2103, 0.6831,  ..., 0.9370, 0.0154, 0.1631]])

In [8]:
a.view(4, 28*28).shape

torch.Size([4, 784])

In [9]:
a.view(4*28, 28).shape

torch.Size([112, 28])

In [10]:
a.view(4*1, 28, 28).shape

torch.Size([4, 28, 28])

In [12]:
b = a.view(4, 784)
b.view(4, 28, 28, 1)

tensor([[[[0.2212],
          [0.8980],
          [0.9834],
          ...,
          [0.2393],
          [0.4832],
          [0.0399]],

         [[0.9621],
          [0.5028],
          [0.7549],
          ...,
          [0.7746],
          [0.9003],
          [0.4492]],

         [[0.7328],
          [0.7749],
          [0.2935],
          ...,
          [0.5952],
          [0.5339],
          [0.4234]],

         ...,

         [[0.6517],
          [0.4782],
          [0.6856],
          ...,
          [0.4450],
          [0.8922],
          [0.9756]],

         [[0.2525],
          [0.9076],
          [0.1235],
          ...,
          [0.4533],
          [0.9786],
          [0.0732]],

         [[0.6077],
          [0.3768],
          [0.2772],
          ...,
          [0.3075],
          [0.6593],
          [0.2300]]],


        [[[0.5197],
          [0.0888],
          [0.5943],
          ...,
          [0.4955],
          [0.8551],
          [0.1113]],

         [[0.0363],
    

In [13]:
a.view(4, 783)

RuntimeError: shape '[4, 783]' is invalid for input of size 3136

# squeeze v.s. unsqueeze

In [14]:
a.shape

torch.Size([4, 1, 28, 28])

In [15]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [16]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [17]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [18]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [19]:
a.unsqueeze(5).shape

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)

In [21]:
a = torch.tensor([1.2, 2.3])
print(a.shape)
a.unsqueeze(-1)

torch.Size([2])


tensor([[1.2000],
        [2.3000]])

In [22]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

In [23]:
# for example
b = torch.rand(32)
f = torch.rand(4, 32, 14, 14)
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)
b.shape

torch.Size([1, 32, 1, 1])

# squeeze

In [24]:
b.shape

torch.Size([1, 32, 1, 1])

In [25]:
b.squeeze().shape

torch.Size([32])

In [26]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [27]:
b.squeeze(1).shape

torch.Size([1, 32, 1, 1])

In [28]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

# expand/expand_as

In [31]:
a = torch.rand(4, 32, 14, 14)
b.shape

torch.Size([1, 32, 1, 1])

In [32]:
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

In [33]:
b.expand(-1, 32, -1, -1).shape

torch.Size([1, 32, 1, 1])

In [34]:
b.expand(-1, 32, -1, -4).shape

torch.Size([1, 32, 1, -4])

# repeat

In [35]:
b.shape

torch.Size([1, 32, 1, 1])

In [36]:
b.repeat(4, 32, 1, 1).shape

torch.Size([4, 1024, 1, 1])

In [37]:
b.repeat(4, 1, 1, 1).shape

torch.Size([4, 32, 1, 1])

In [38]:
b.repeat(4, 1, 32, 32).shape

torch.Size([4, 32, 32, 32])

# .t

In [40]:
b.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [42]:
a = torch.randn(3, 4)
a.t()

tensor([[ 1.7666, -0.5852, -0.2990],
        [ 0.0390,  1.5779,  0.7180],
        [-0.8842, -1.3869, -0.6083],
        [-0.7004, -1.1548, -0.5403]])

# Transpose

In [49]:
# print(a)
a = torch.rand(4,3,32,32)
a.shape

torch.Size([4, 3, 32, 32])

In [50]:
a1 = a.tanspose(1, 3).view(4, 3*32*32).view(4, 3, 32, 32)

AttributeError: 'Tensor' object has no attribute 'tanspose'

In [52]:
a1 = a.transpose(1, 3).contiguous().view(4, 3*32*32).view(4, 3, 32, 32)
a1.shape

torch.Size([4, 3, 32, 32])

In [53]:
a2 = a.transpose(1, 3).contiguous().view(4, 3*32*32).view(4, 32, 32, 3).transpose(1, 3)
a2.shape

torch.Size([4, 3, 32, 32])

In [54]:
torch.all(torch.eq(a, a1))

tensor(0, dtype=torch.uint8)

# permute

In [55]:
a =torch.rand(4, 3, 28, 28)
a.transpose(1, 3).shape

torch.Size([4, 28, 28, 3])

In [56]:
b = torch.rand(4, 3, 28, 32)
b.transpose(1, 3).shape

torch.Size([4, 32, 28, 3])

In [58]:
b.transpose(1, 3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [59]:
b.permute(0, 2, 3, 1).shape

torch.Size([4, 28, 32, 3])