# basic:add/minus/multiply/divide

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.rand(4)
a + b

tensor([[1.0159, 1.3685, 0.8189, 0.8325],
        [0.6895, 1.7133, 1.3606, 1.1423],
        [0.6340, 1.3804, 0.9535, 0.5634]])

In [4]:
torch.add(a, b)

tensor([[1.5443, 1.3971, 1.1288, 1.5314],
        [1.0949, 0.5202, 1.0437, 1.3269],
        [0.8517, 1.3154, 1.0404, 1.2326]])

In [3]:
torch.all(torch.eq(a-b, torch.sub(a, b)))

tensor(1, dtype=torch.uint8)

In [7]:
torch.all(torch.eq(a*b, torch.mul(a, b)))

tensor(1, dtype=torch.uint8)

In [10]:
a = torch.full([2, 2], 3)
a

tensor([[3., 3.],
        [3., 3.]])

In [12]:
b = torch.ones(2, 2)
b

tensor([[1., 1.],
        [1., 1.]])

In [16]:
# only for 2d
torch.mm(a, b) 

tensor([[6., 6.],
        [6., 6.]])

In [14]:
torch.matmul(a, b)

tensor([[6., 6.],
        [6., 6.]])

In [15]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [17]:
a = torch.rand(4, 784)
x = torch.rand(4, 784)
w = torch.rand(512, 784)
(x@w.t()).shape

torch.Size([4, 512])

In [18]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)
torch.mm(a, b).shape

RuntimeError: matrices expected, got 4D, 4D tensors at ..\aten\src\TH/generic/THTensorMath.cpp:956

In [19]:
torch.matmul(a, b).shape

torch.Size([4, 3, 28, 32])

In [21]:
b = torch.rand(4, 1, 64, 32)
torch.matmul(a, b).shape

torch.Size([4, 3, 28, 32])

In [22]:
b = torch.rand(4, 64, 32)
torch.matmul(a, b).shape

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

# power

In [23]:
a = torch.full([2, 2], 3)
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [25]:
a**2

tensor([[9., 9.],
        [9., 9.]])

In [26]:
aa = a**2
aa.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [27]:
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [28]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

# exp log

In [30]:
a = torch.exp(torch.ones(2, 2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [31]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

# approximation

In [34]:
a = torch.tensor(3.14)
a.floor(),a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [35]:
a = torch.tensor(3.499)
a.round()

tensor(3.)

In [36]:
a = torch.tensor(3.5)
a.round()

tensor(4.)

# clamp

In [37]:
grad = torch.rand(2, 3)*15
grad.max()

tensor(12.3839)

In [38]:
grad.median()

tensor(10.9865)

In [39]:
grad.clamp(10)

tensor([[12.3839, 10.0000, 10.0000],
        [11.8239, 12.2194, 10.9865]])

In [40]:
grad

tensor([[12.3839,  6.9299,  5.4770],
        [11.8239, 12.2194, 10.9865]])

In [41]:
grad.clamp(0, 10)

tensor([[10.0000,  6.9299,  5.4770],
        [10.0000, 10.0000, 10.0000]])