In [3]:
import torch

# normal

In [4]:
a = torch.full([8], 1)
b = a.view(2, 4)
c = a.view(2, 2, 2)
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [6]:
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [7]:
a.norm(2), b.norm(2), b.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [8]:
b.norm(1, dim=1)

tensor([4., 4.])

In [9]:
b.norm(2, dim=1)

tensor([2., 2.])

In [11]:
b.norm(1, dim=0), b.norm(2, dim=0)

(tensor([2., 2., 2., 2.]), tensor([1.4142, 1.4142, 1.4142, 1.4142]))

In [5]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [6]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

# mean,sum,min,max,pro

In [13]:
a = torch.arange(8).view(2, 4).float()
print(a)

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])


In [10]:
a.min(), a.max(),a.mean(),a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [11]:
a.sum()

tensor(28.)

In [12]:
a.argmax(),a.argmin()

(tensor(7), tensor(0))

In [15]:
a = a.view(1, 2, 4)
print(a)

tensor([[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]])


In [16]:
a.argmax()

tensor(7)

In [17]:
a.argmin()

tensor(0)

In [19]:
a = torch.rand(2, 3, 4)
print(a)
a.argmax()

tensor([[[0.5373, 0.6463, 0.1253, 0.9813],
         [0.7483, 0.0677, 0.4321, 0.3067],
         [0.3899, 0.3393, 0.3646, 0.6462]],

        [[0.2757, 0.1835, 0.1511, 0.2725],
         [0.1781, 0.0841, 0.1663, 0.3183],
         [0.4571, 0.1766, 0.8351, 0.3891]]])


tensor(3)

In [21]:
a = torch.randn(4, 10)
print(a)
a[0]

tensor([[ 1.6910, -0.4140, -0.6805,  0.0066,  0.7547,  0.8518, -0.2222,  0.7704,
          0.3089,  1.0860],
        [ 0.1682, -0.6809, -1.3609,  1.8671, -0.5153, -0.8362,  0.4805, -0.7835,
          0.3148,  0.4846],
        [ 0.7997, -0.6404,  0.8982, -0.6152, -0.8298,  0.8057, -0.2584, -0.8535,
         -0.0304, -1.6390],
        [ 1.1800,  1.0247, -2.0674,  0.3555, -2.2574, -1.6166, -0.8134,  0.7567,
         -0.5606,  0.1487]])


tensor([ 1.6910, -0.4140, -0.6805,  0.0066,  0.7547,  0.8518, -0.2222,  0.7704,
         0.3089,  1.0860])

In [22]:
a.argmax()

tensor(13)

In [25]:
a.argmax(dim=1)

tensor([0, 3, 2, 0])

In [26]:
a

tensor([[ 1.6910, -0.4140, -0.6805,  0.0066,  0.7547,  0.8518, -0.2222,  0.7704,
          0.3089,  1.0860],
        [ 0.1682, -0.6809, -1.3609,  1.8671, -0.5153, -0.8362,  0.4805, -0.7835,
          0.3148,  0.4846],
        [ 0.7997, -0.6404,  0.8982, -0.6152, -0.8298,  0.8057, -0.2584, -0.8535,
         -0.0304, -1.6390],
        [ 1.1800,  1.0247, -2.0674,  0.3555, -2.2574, -1.6166, -0.8134,  0.7567,
         -0.5606,  0.1487]])

# dim,keepdim

In [28]:
a.max(dim=1)

torch.return_types.max(
values=tensor([1.6910, 1.8671, 0.8982, 1.1800]),
indices=tensor([0, 3, 2, 0]))

In [31]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[1.6910],
        [1.8671],
        [0.8982],
        [1.1800]]),
indices=tensor([[0],
        [3],
        [2],
        [0]]))

In [32]:
a.argmax(dim=1, keepdim=True)

tensor([[0],
        [3],
        [2],
        [0]])

# Top-k or k-th

In [35]:
a.topk(3,dim=1)

torch.return_types.topk(
values=tensor([[1.6910, 1.0860, 0.8518],
        [1.8671, 0.4846, 0.4805],
        [0.8982, 0.8057, 0.7997],
        [1.1800, 1.0247, 0.7567]]),
indices=tensor([[0, 9, 5],
        [3, 9, 6],
        [2, 5, 0],
        [0, 1, 7]]))

In [36]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[-0.6805, -0.4140, -0.2222],
        [-1.3609, -0.8362, -0.7835],
        [-1.6390, -0.8535, -0.8298],
        [-2.2574, -2.0674, -1.6166]]),
indices=tensor([[2, 1, 6],
        [2, 5, 7],
        [9, 7, 4],
        [4, 2, 5]]))

In [37]:
a.kthvalue(8, dim=1)

torch.return_types.kthvalue(
values=tensor([0.8518, 0.4805, 0.7997, 0.7567]),
indices=tensor([5, 6, 0, 7]))

# compare

In [38]:
a > 0 

tensor([[1, 0, 0, 1, 1, 1, 0, 1, 1, 1],
        [1, 0, 0, 1, 0, 0, 1, 0, 1, 1],
        [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
        [1, 1, 0, 1, 0, 0, 0, 1, 0, 1]], dtype=torch.uint8)

In [39]:
torch.gt(a, 0)

tensor([[1, 0, 0, 1, 1, 1, 0, 1, 1, 1],
        [1, 0, 0, 1, 0, 0, 1, 0, 1, 1],
        [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
        [1, 1, 0, 1, 0, 0, 0, 1, 0, 1]], dtype=torch.uint8)

In [40]:
a != 0

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=torch.uint8)

In [41]:
a = torch.ones(2,3)
b = torch.randn(2,3)
torch.eq(a,b)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)

In [42]:
torch.eq(a, a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.uint8)

In [43]:
torch.equal(a,a)

True