# advanced operation

### where

In [1]:
import torch

In [4]:
cond = torch.rand([2,2])
a = torch.zeros([2,2])
b = torch.ones([2,2])
print(cond, a, b)

tensor([[0.0902, 0.4060],
        [0.2628, 0.5734]]) tensor([[0., 0.],
        [0., 0.]]) tensor([[1., 1.],
        [1., 1.]])


In [5]:
torch.where(cond>0.5, a, b)

tensor([[1., 1.],
        [1., 0.]])

### gather

In [9]:
prob = torch.randn(4, 10)
idx = prob.topk(dim=1, k=3)
print(prob)
print(idx)

tensor([[ 2.6434e-03,  1.4170e+00, -2.9069e-02, -5.5754e-02,  1.6232e+00,
          5.0729e-01, -6.6894e-01, -1.8245e-01, -1.1502e-01, -1.4409e+00],
        [ 1.6687e+00,  3.7441e-01,  4.4130e-01, -1.2576e+00,  8.5769e-01,
         -4.5603e-01, -9.7807e-02,  2.6097e-01,  3.5275e-01,  2.4614e-01],
        [-6.6616e-01, -8.0910e-01, -8.0176e-01, -1.7251e+00,  1.3693e-01,
         -1.2411e+00,  7.7146e-01,  5.6614e-01, -1.1644e+00, -1.4633e+00],
        [-4.4846e-01,  1.0492e+00, -2.9411e+00,  1.7419e+00, -8.7228e-01,
         -3.9410e-01,  1.3997e+00, -1.6236e+00, -1.9742e-01, -3.6099e-01]])
torch.return_types.topk(
values=tensor([[1.6232, 1.4170, 0.5073],
        [1.6687, 0.8577, 0.4413],
        [0.7715, 0.5661, 0.1369],
        [1.7419, 1.3997, 1.0492]]),
indices=tensor([[4, 1, 5],
        [0, 4, 2],
        [6, 7, 4],
        [3, 6, 1]]))


In [10]:
idx[1]

tensor([[4, 1, 5],
        [0, 4, 2],
        [6, 7, 4],
        [3, 6, 1]])