In [1]:
import numpy as np
import torch

In [3]:
# 创建tensor
# 1.import from numpy
a = np.array([2, 3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [7]:
a = np.ones([2, 3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [8]:
# 2.import from list
torch.tensor([2., 3.2])

tensor([2.0000, 3.2000])

In [9]:
torch.FloatTensor([2., 3.2])

tensor([2.0000, 3.2000])

In [11]:
torch.tensor([[2., 3.2],
              [1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

In [12]:
# uninitialized
torch.empty(1)

tensor([2.3694e-38])

In [15]:
torch.Tensor(2, 3)

tensor([[-1.4975e+12,  4.5912e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])