indexing

In [9]:
import torch

In [6]:
a = torch.rand(4, 3, 28, 28)
a[0].shape

torch.Size([3, 28, 28])

In [7]:
a[0,0].shape

torch.Size([28, 28])

In [14]:
a[0,0,2,4]

tensor(0.3334)

select first/last N

In [13]:
a.shape

torch.Size([4, 3, 28, 28])

In [12]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [15]:
a[:2,:1,:,:].shape

torch.Size([2, 1, 28, 28])

In [16]:
a[:2,1:,:,:].shape

torch.Size([2, 2, 28, 28])

In [17]:
a[:2,-1:,:,:].shape

torch.Size([2, 1, 28, 28])

select by steps

In [18]:
a[:,:,0:28:2,0:28:2].shape

torch.Size([4, 3, 14, 14])

In [19]:
a[:,:,::2,::2].shape

torch.Size([4, 3, 14, 14])

select by specific index

In [20]:
a.shape

torch.Size([4, 3, 28, 28])

In [21]:
a.index_select(2, torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [22]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

...

In [23]:
a.shape

torch.Size([4, 3, 28, 28])

In [24]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [25]:
a[0, ...].shape

torch.Size([3, 28, 28])

In [26]:
a[:,1,...].shape

torch.Size([4, 28, 28])

In [27]:
a[...,:2].shape

torch.Size([4, 3, 28, 2])

select by mask

In [29]:
x = torch.randn(3, 4)
print(x)

tensor([[-0.6863,  0.3999,  1.0012, -1.7611],
        [-0.8240,  0.7031, -0.5182,  1.1678],
        [ 0.7824,  0.7429, -0.0870,  0.6370]])


In [31]:
mask = x.ge(0.5)
print(mask)

tensor([[0, 0, 1, 0],
        [0, 1, 0, 1],
        [1, 1, 0, 1]], dtype=torch.uint8)


In [32]:
torch.masked_select(x, mask)

tensor([1.0012, 0.7031, 1.1678, 0.7824, 0.7429, 0.6370])

In [35]:
torch.masked_select(x, mask).shape

torch.Size([6])

select by flatten index

In [34]:
src = torch.tensor([
    [4,3,5],
    [6,7,8]
])